require "milosz.options"
require "milosz.plugins"
require "milosz.keymaps"
require "milosz.colorscheme"
require "milosz.tree"
require "milosz.treesitter"
require "milosz.alpha"
require "milosz.cmp"
require "milosz.lsp"
require "milosz.bufferline"
require "milosz.spotify"
require "milosz.autopairs"
require "milosz.toggleterm"
require "milosz.lualine"

