require "nvim.options"
require "nvim.plugins"
require "nvim.keymaps"
require "nvim.colorscheme"
require "nvim.tree"
require "nvim.treesitter"
require "nvim.alpha"
require "nvim.cmp"
require "nvim.lsp"
require "nvim.bufferline"
require "nvim.spotify"
require "nvim.autopairs"
require "nvim.toggleterm"
require "nvim.lualine"

